exp:
  expname: S12_021_256_60
  expdir: ./logs/
  datadir: ./data/S12_021_256_60.pickle

is_dynet: True
num_phases: 60
dy_network:
  net_type: dyc #
  num_layers: 4
  hidden_dim: 32
  skips: [2]
  out_dim: 1
  last_activation: softplus
  bound: 0.3

dy_encoder:
  encoding: HashGrid4D
  input_dim: 3 #
  num_levels: 16
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19

render:
  n_samples: 320
  n_fine: 0
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600

train:
  epoch: 50000
  n_batch: 1
  n_rays: 1024
  lrate: 0.01
  lrate_gamma: 0.01
  lrate_step: 1501
  resume: True
  isTVloss: True

log:
  i_eval: 1000
  i_save: 10000

