# Parameters to setup CT simulation.

# dataset
numTrain: 100
numVal: 50

# System configuration
DSD: 1500.0  # Distance Source Detector      (mm)
DSO: 1000.0  # Distance Source Origin        (mm)

# Detector parameters
nDetector: # Number of pixels              (px)
- 768
- 1024
dDetector: # Size of each pixel            (mm)
- 0.6
- 0.6

# Image parameters
nVoxel: # Number of voxels              (vx)
- 512
- 512
- 142
dVoxel: # size of each voxel            (mm)
- 1
- 1
- 3

# Offsets
offOrigin: # Offset of image from origin   (mm)
- 0 # x direction
- 0 # y direction
- 0 # z direction
offDetector: # Offset of Detector (only in two direction)            (mm)
- 0 # u direction
- 0 # v direction

# Auxiliary
accuracy: 0.5 # Accuracy of FWD proj          (vx/sample)

# Mode
mode: cone # X-ray source mode parallel/cone
filter: null

# Angles
totalAngle: 360.0 # Total angle  (degree)
startAngle: 0.0 # Start Angle (degree)
randomAngle: False

# CT
convert: False
rescale_slope: 1.0
rescale_intercept: 0.0
normalize: False

# Noise
noise: 0
